version: '3'
services:

  db:
    image: postgres
    restart: always
    ports:
      - "25432:5432"

    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=user
      - POSTGRES_DB=user_db

  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080